var items = [
    {
        "id": "1",
        "name": "Pokemon card Pokecarizardon Hikaru Bangiras",
        "image_urls": "item-1.1.png, item-1.2.png, item-1.3.png",
        "starting_price": 682,
        "highest_bidder": "8",
        "product_descripton": "I think it 's something I collected when I was little thing Hikaru Bangiras with 3 Charizard marks ← Is this the most valuable? I honestly don't know the market price other than without the Kirapippi mark . Lizardon is injured. Others are in moderate condition for those days. The items in the box are mostly normal ones. Please be sure to look at the image and be satisfied before bidding.",
        "start_date": "2023/11/03",
        "end_date": "2023/11/06",
        "category": "collection",
        "status": "completed"
    },
    {
        "id": "2",
        "name": "Unopened Ichiban Kuji Dragon Ball VS Omnibus F Award MASTERLISE Majin Buu figure",
        "image_urls": "item-2.1.png, item-2.2.png, item-2.3.png",
        "starting_price": 204,
        "highest_bidder": "0",
        "product_descripton": "If you wish to bundle the items together, please be sure to make a \"collection request\".\r\nBundled items are limited to items that have been successfully bid within 52 hours from the first successful bid.\r\nPlease note that if there is no request for a summary, the system will not be able to accept the summary outside the period.\r\n\r\nIn addition, after accepting a summary request, you will not be able to cancel any orders due to the Yahoo Auctions system.\r\nPlease note that if payment is not made, we will send an invoice to your address.",
        "start_date": "2023/11/03",
        "end_date": "2023/11/05",
        "category": "collection",
        "status": "completed"
    },
    {
        "id": "3",
        "name": "Ichiban Kuji Dragon Ball Super Super Hero Double Chance Campaign Shenron Figure Double Chance Color ver",
        "image_urls": "item-3.1.png, item-3.2.png, item-3.3.png",
        "starting_price": 2046,
        "highest_bidder": "0",
        "product_descripton": "Big final price reduction.\r\nThere are no plans to reduce the price further, so please take this opportunity to buy it!\r\n\r\nThis item is imported from Korea.\r\nIt will be the real thing that won in October.\r\nIn Japan, BANDAI can prove that you won, but in Korea, the certificate was not included from the beginning.\r\nWe distributed the same product in South Korea in October, but if you have any concerns, please contact BANDAI.\r\nAlthough it is unopened, there may be scratches that are overlooked.\r\nPlease purchase only those who can understand.",
        "start_date": "2023/11/01",
        "end_date": "2023/11/06",
        "category": "collection",
        "status": "upcoming"
    },
    {
        "id": "4",
        "name": "1/18 AUTOART auto art PAGANI ZONDA R Nurburgring Lap Time Record Edition 78263 Pagani Zonda lap time record AMG",
        "image_urls": "item-4.1.png, item-4.2.png, item-4.3.png",
        "starting_price": 1300,
        "highest_bidder": "0",
        "product_descripton": "Thank you for your interest in our products.\r\nPlease read below before bidding. [ Product\r\n\r\ndescription] Brand/Manufacturer :\r\nAUTOART\r\nModel number: 78263 Carbon Black 1000pcs . Note: All the items in the photo are for sale. Since it was originally planned to be displayed, the left and right mirrors and the driver are in a bag and unopened. [Others] Please ask any questions. Please also check the self-introduction sentence.",
        "start_date": "2023/11/02",
        "end_date": "2023/11/08",
        "category": "collection",
        "status": "upcoming"
    },
    {
        "id": "5",
        "name": "BE@RBRICK IRON MAN MARK 50 1000% Bearbrick new unopened genuine product",
        "image_urls": "item-5.1.png, item-5.2.png, item-5.3.png",
        "starting_price": 500,
        "highest_bidder": "0",
        "product_descripton": "This is the BE@RBRICK IRON MAN MARK 50 1000% purchased at Medicom Toy! !　\r\nIt will be a completely new unopened product and a completely genuine product!\r\n\r\nSince it is a popular Bear Brick Iron Man series, please take this opportunity ^ _ ^\r\n\r\nIt is also exhibited on another site, so please hurry! ! ! Bearbrick has a track record of many transactions",
        "start_date": "2023/11/04",
        "end_date": "2023/11/06",
        "category": "furniture",
        "status": "upcoming"
    },
    {
        "id": "6",
        "name": "Beautiful Iznik pattern",
        "image_urls": "item-6.1.png, item-6.2.png, item-6.3.png",
        "starting_price": 400,
        "highest_bidder": "0",
        "product_descripton": "Material: Pile part of the carpet: 100% wool warp (the tufted part: 100% cotton (Most Turkish carpets use 100% cotton for the warp to increase strength. The same is true for ultra-luxury Persian carpets). The carpet part is made of 100% wool.Extremely cheap ones and machine woven ones often use synthetic fiber for the pile part of the carpet.In addition, cheap silk sold under the name of silk uses bamboo. Please note that some of the carpets are made of imitation silk.To ensure that you choose the right carpet that will last for a long time, we recommend that you purchase the carpet from a specialty store.A good carpet is like clothes and shoes and is cheap. Good things can be used for a lifetime.Radik carpets are one rank higher than Kayseri Even machine woven carpets cost more than 30,000 yen per square meter.This is a handwoven carpet.",
        "start_date": "2023/11/05",
        "end_date": "2023/11/05",
        "category": "furniture",
        "status": "upcoming"
    },
    {
        "id": "7",
        "name": "IZ61577F Italy CL italia Bureau sideboard Art Nouveau Classic wood carving desk cabinet Art Nouveau luxury",
        "image_urls": "item-7.1.png, item-7.2.png, item-7.3.png",
        "starting_price": 753,
        "highest_bidder": "0",
        "product_descripton": "CL italia CL italia is a classic reproduction brand that specializes in recreating early 20th century Art Nouveau and Art Deco furniture, established in 1956 by woodworker Livio Colombo. An ultra-luxury furniture brand that protects traditional Italian furniture-making techniques and manufactures decorative furniture that is unparalleled in artistry, and has received high acclaim from all over the world.",
        "start_date": "2023/11/04",
        "end_date": "2023/11/06",
        "category": "furniture",
        "status": "upcoming"
    },
    {
        "id": "8",
        "name": "IZ57528F Nathan Circle Sideboard Vintage Teak Scandinavian Style Sideboard Mid Century Vintage UK Nathan",
        "image_urls": "item-8.1.png, item-8.2.png, item-8.3.png",
        "starting_price": 605,
        "highest_bidder": "0",
        "product_descripton": "It is a circle sideboard by Nathan (Nathan), one of the furniture brands representing the mid-century of England.\r\n\r\nAn elegant vintage sideboard with a British flair. It is a simple design based on Scandinavian style, but the circle pattern on the front door is very impressive. Among Nathan's sideboards, it is a particularly popular and rare model, and the fact that it is less distributed than G-PLAN and McIntosh also tickles the collector's heart.",
        "start_date": "2023/11/04",
        "end_date": "2023/11/06",
        "category": "furniture",
        "status": "upcoming"
    },
    {
        "id": "9",
        "name": "Sophia 1008-1W-5F102B Sofa 1 Seater Sofa for 1 Person Antique Style 1 Seater Sofa 1 Person High Back Sofa Brown x Green Damask",
        "image_urls": "item-9.1.png, item-9.2.png, item-9.3.png",
        "starting_price": 350,
        "highest_bidder": "0",
        "product_descripton": "Pretty and beautiful sofa.\r\nA feminine style with an impressive round shape.\r\nThe depth is also deep, you can relax and relax.",
        "start_date": "2023/10/31",
        "end_date": "2023/11/07",
        "category": "furniture",
        "status": "sponsored"
    },
    {
        "id": "10",
        "name": "Period Maki-e \"Shochiku-plum Maki-e Kotansu Ten kinds of incense sticks/Ink stone box/Blue shell silver leaf board\"",
        "image_urls": "item-10.1.png, item-10.2.png, item-10.3.png",
        "starting_price": 420,
        "highest_bidder": "0",
        "product_descripton": "It is about 14.7 in length and 24.9 in width and 22.4 in height.\r\nThere are threads etc. in multiple places that you want to pull out.\r\nThere was one crack.",
        "start_date": "2023/10/30",
        "end_date": "2023/11/06",
        "category": "antique",
        "status": "sponsored"
    },
    {
        "id": "11",
        "name": "Wholesale Home Decor Bronze Metal Art Crafts Sculpture For Sale",
        "image_urls": "item-11.1.png, item-11.2.png, item-11.3.png",
        "starting_price": 577,
        "highest_bidder": "0",
        "product_descripton": "Bronze Sculptures, Bronze Metal Crafts, Bronze Gift Crafts, Bronze Arts Home Decor And figurines can be an eye-catching part of any decoration in any surrounding. . Whether choosing for a personal aesthetic or to embellish a landscape, Bronze sculptures Bronze metal crafts, bronze Gift crafts, bronze arts home decor is a popular one. part of interior and exterior decoration. They are, however, not merely decorative, but the expression of the owner's personality. A-various types of bronze sculptures, Bronze metal crafts, bronze Gift crafts, bronze arts home decor And figurines, including Viennese nudes, Greek statues, and garden sculptures, are available in our Copper Store. Regardless of your aesthetic, style, or desired size, there is definitely a bronze sculpture , Bronze Metal Crafts, Bronze Crafts Gift, Bronze Art Home Decor To match fit your needs.",
        "start_date": "2023/11/21",
        "end_date": "2023/12/14",
        "category": "antique",
        "status": "sponsored"
    },
    {
        "id": "12",
        "name": "Custom Sculpture Bronze Horse Animal Statue Metal Sculpture Arts Crafts Indoor Decoration",
        "image_urls": "item-12.1.png, item-12.2.png, item-12.3.png",
        "starting_price": 108,
        "highest_bidder": "0",
        "product_descripton": "Horse statue.Dong/dong/dong.Sculpture interior decoration.Electroplate.All De Sign S Can be customized as customer's request",
        "start_date": "2023/11/21",
        "end_date": "2023/12/21",
        "category": "antique",
        "status": "sponsored"
    },
    {
        "id": "13",
        "name": "Factory price garden statue metal life size Brass lady woman sculpture",
        "image_urls": "item-13.1.png, item-13.2.png, item-13.3.png",
        "starting_price": 599,
        "highest_bidder": "0",
        "product_descripton": "Bronze/Copper/Brass.Normal Height 1.3M to 1.8M or Customized.Original color/ shinny golden/imitated ancient/green/black. Decoration or gift. Hand-made with Surface Polishing. Valid with temperature from -20℃ to 40℃. Away from hailstone, frequently rainy day, heavy snowy place.For family hall/indoor/ temple/monastery/fane/land scape/ theme place and etc.Use Trade Assurance to Get Extra Favor! Or by L/C, T/T",
        "start_date": "2023/10/06",
        "end_date": "2023/11/15",
        "category": "antique",
        "status": "sponsored"
    },
    {
        "id": "14",
        "name": "Coconut shell bowl with flower carving art",
        "image_urls": "item-14.1.png, item-14.2.png, item-14.3.png",
        "starting_price": 804,
        "highest_bidder": "0",
        "product_descripton": "Coconut shell kitchen utensils are a completely natural product, handmade from coconut shells, without PU paint, chemically marinated, with a strong and durable thickness. Coconut shell bowl has high durability, nowadays people use natural Oganic products to protect the health of their family and themselves.",
        "start_date": "2023/11/09",
        "end_date": "2023/12/09",
        "category": "antique",
        "status": "sponsored"
    },
    {
        "id": "15",
        "name": "Rare gold seal of emperor Minh Mang",
        "image_urls": "item-15.1.png, item-15.2.png, item-15.3.png",
        "starting_price": 2500,
        "highest_bidder": "0",
        "product_descripton": "VIETNAM, Dynastie Nguyen (1802-1945).Rare sceau en or Kim Bao billion (金寶璽) de l'Empereur Minh Mang (1791-1841).Important Vietnamese imperial seal in gold, composed of a double superimposed square base, the grip taking the form of a dragon with five claws rolled up on itself and whose raised head bears the character 王 (vương), meaning king, incised . the tail raised at the back of the head and ending in a spiral, a protruding dorsal ridge adorning the scaly body of the animal along its entire length, the head bristling with stag horns revealing a lion's muzzle, the canines exposed. The four legs firmly anchored and ending in five claws.",
        "start_date": "2022/11/10",
        "end_date": "2022/12/21",
        "category": "antique",
        "status": "popular"
    },
    {
        "id": "16",
        "name": "3D die strucking antique brass coins old bronze coins for sale",
        "image_urls": "item-16.1.png, item-16.2.png, item-16.3.png",
        "starting_price": 100,
        "highest_bidder": "0",
        "product_descripton": "2D/3D, one side logo or double.Printing/(black) Laser engraving/Etch etc.Square/rectangle/round ETC (customized).Iron/copper/copper/Zinc alloy etc.poly bag/bubble bag/opp bag/plastic box/gift box, etc.",
        "start_date": "2023/11/08",
        "end_date": "2023/12/21",
        "category": "antique",
        "status": "popular"
    },
    {
        "id": "17",
        "name": "Queen of the wedding chair",
        "image_urls": "item-17.1.png, item-17.2.png, item-17.3.png",
        "starting_price": 380,
        "highest_bidder": "0",
        "product_descripton": "Dining, hotel, restaurant, event, home",
        "start_date": "2022/11/07",
        "end_date": "2022/12/02",
        "category": "antique",
        "status": "popular"
    },
    {
        "id": "18",
        "name": "Vintage Vintage High Quality Custom Blue And White Ceramic Coffee Cup With Saucer",
        "image_urls": "item-18.1.png, item-18.2.png, item-18.3.png",
        "starting_price": 150,
        "highest_bidder": "0",
        "product_descripton": "High quality custom blue and white ceramic coffee cup with saucer",
        "start_date": "2022/11/11",
        "end_date": "2022/12/03",
        "category": "antique",
        "status": "popular"
    },
    {
        "id": "19",
        "name": "Nguyen Dynasty mandarin hat and Nhat Binh shirt",
        "image_urls": "item-19.1.png, item-19.2.png, item-19.3.png",
        "starting_price": 6834,
        "highest_bidder": "1",
        "product_descripton": "The manager and Nhat Binh's robes were assessed by an appraisal council consisting of scientists, artisans, and antique collectors dating back to the 19th and early 20th centuries, associated with the Nguyen court life.",
        "start_date": "2023/04/17",
        "end_date": "2023/12/12",
        "category": "antique",
        "status": "popular"
    },
    {
        "id": "20",
        "name": "Men's Coldker Long Sleeve Sweater Outfits , Medieval Pirates Scooter Outfits Scottish Style",
        "image_urls": "item-20.1.png, item-20.2.png, item-20.3.png",
        "starting_price": 1416,
        "highest_bidder": "0",
        "product_descripton": ", size: S-3XL, custom made for small MOQ",
        "start_date": "2022/10/09",
        "end_date": "2022/12/07",
        "category": "antique",
        "status": "popular"
    }
]